# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_commit_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 116)
        Dialog.setMaximumSize(QtCore.QSize(400, 116))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.noButton = QtWidgets.QPushButton(Dialog)
        self.noButton.setObjectName("noButton")
        self.gridLayout_2.addWidget(self.noButton, 1, 1, 1, 1)
        self.yesButton = QtWidgets.QPushButton(Dialog)
        self.yesButton.setObjectName("yesButton")
        self.gridLayout_2.addWidget(self.yesButton, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Подтвердите действие"))
        self.label.setText(_translate("Dialog", "Вы уверены что хотите удалить?"))
        self.noButton.setText(_translate("Dialog", "Нет"))
        self.yesButton.setText(_translate("Dialog", "Да"))
