# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_error_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 90)
        Dialog.setMinimumSize(QtCore.QSize(385, 90))
        Dialog.setMaximumSize(QtCore.QSize(385, 88))
        self.exportErrorLabel = QtWidgets.QLabel(Dialog)
        self.exportErrorLabel.setGeometry(QtCore.QRect(0, 10, 381, 51))
        self.exportErrorLabel.setText("")
        self.exportErrorLabel.setObjectName("exportErrorLabel")
        self.okErrorButton = QtWidgets.QPushButton(Dialog)
        self.okErrorButton.setGeometry(QtCore.QRect(300, 60, 75, 23))
        self.okErrorButton.setObjectName("okErrorButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ошибка"))
        self.okErrorButton.setText(_translate("Dialog", "ОК"))
