# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_commit_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 90)
        Dialog.setMinimumSize(QtCore.QSize(385, 90))
        Dialog.setMaximumSize(QtCore.QSize(385, 90))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 361, 51))
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(300, 60, 75, 23))
        self.okButton.setMinimumSize(QtCore.QSize(75, 23))
        self.okButton.setMaximumSize(QtCore.QSize(75, 23))
        self.okButton.setObjectName("okButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Успешно"))
        self.label.setText(_translate("Dialog", "Экспорт прошел успешно. Файл находится в папке с программой. \n"
"Название: logins.csv"))
        self.okButton.setText(_translate("Dialog", "ОК"))
