# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_dialog_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(295, 315)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.generateUpdatePasswordCheckBox = QtWidgets.QCheckBox(Dialog)
        self.generateUpdatePasswordCheckBox.setObjectName("generateUpdatePasswordCheckBox")
        self.verticalLayout_2.addWidget(self.generateUpdatePasswordCheckBox)
        self.specialSymbolsUpdateCheckBox = QtWidgets.QCheckBox(Dialog)
        self.specialSymbolsUpdateCheckBox.setObjectName("specialSymbolsUpdateCheckBox")
        self.verticalLayout_2.addWidget(self.specialSymbolsUpdateCheckBox)
        self.numbersUpdateCheckBox = QtWidgets.QCheckBox(Dialog)
        self.numbersUpdateCheckBox.setObjectName("numbersUpdateCheckBox")
        self.verticalLayout_2.addWidget(self.numbersUpdateCheckBox)
        self.lengthUpdatePasswordLabel = QtWidgets.QLabel(Dialog)
        self.lengthUpdatePasswordLabel.setObjectName("lengthUpdatePasswordLabel")
        self.verticalLayout_2.addWidget(self.lengthUpdatePasswordLabel)
        self.lengthUpdatePasswordLine = QtWidgets.QLineEdit(Dialog)
        self.lengthUpdatePasswordLine.setObjectName("lengthUpdatePasswordLine")
        self.verticalLayout_2.addWidget(self.lengthUpdatePasswordLine)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commitUpdateButton = QtWidgets.QPushButton(Dialog)
        self.commitUpdateButton.setObjectName("commitUpdateButton")
        self.horizontalLayout.addWidget(self.commitUpdateButton)
        self.generateUpdateButton = QtWidgets.QPushButton(Dialog)
        self.generateUpdateButton.setObjectName("generateUpdateButton")
        self.horizontalLayout.addWidget(self.generateUpdateButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.serviceUpdateLine = QtWidgets.QLineEdit(Dialog)
        self.serviceUpdateLine.setObjectName("serviceUpdateLine")
        self.verticalLayout.addWidget(self.serviceUpdateLine)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.loginUpdateLine = QtWidgets.QLineEdit(Dialog)
        self.loginUpdateLine.setObjectName("loginUpdateLine")
        self.verticalLayout.addWidget(self.loginUpdateLine)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.passwordUpdateLine = QtWidgets.QLineEdit(Dialog)
        self.passwordUpdateLine.setObjectName("passwordUpdateLine")
        self.verticalLayout.addWidget(self.passwordUpdateLine)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Введите данные"))
        self.generateUpdatePasswordCheckBox.setText(_translate("Dialog", "Сгенерировать пароль"))
        self.specialSymbolsUpdateCheckBox.setText(_translate("Dialog", "Специальные символы"))
        self.numbersUpdateCheckBox.setText(_translate("Dialog", "Цифры"))
        self.lengthUpdatePasswordLabel.setText(_translate("Dialog", "Длина пароля (От 8 до 32):"))
        self.commitUpdateButton.setText(_translate("Dialog", "Подтвердить"))
        self.generateUpdateButton.setText(_translate("Dialog", "Сгенерировать"))
        self.label.setText(_translate("Dialog", "Сервис"))
        self.label_2.setText(_translate("Dialog", "Логин"))
        self.label_3.setText(_translate("Dialog", "Новый пароль"))
